version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      MONGO_URI: mongodb://root:ZGUsNOoxPqNdnhhL@services.irn2.chabokan.net:59230/admin
      TOKEN_SECRET: avattech
      TOKEN_EXPIRES_IN: 86400
    restart: always
